services:
  - type: web
    name: secure-vote-api
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd server && node index.mjs
    envVars:
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health 