services:
  - type: web
    name: secure-vote-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health 